apiVersion: v1
kind: Pod
metadata:
  name: liveness-tcp
spec:
  containers:
  - name: redis
    image: redis:7.0
    ports:
    - containerPort: 6379
    livenessProbe:
      tcpSocket:
        port: 6379       # Redis 포트
      initialDelaySeconds: 5
      periodSeconds: 10

