apiVersion: v1
kind: Pod
metadata:
  name: pvc-local-pod
spec:
  containers:
  - name: test
    image: busybox
    command: ["sh","-c"]
    args: ["echo 로컬 패스 프로비저너 테스트! > /data/test.txt && sleep 3600"]
    volumeMounts:
    - name: data
      mountPath: /data
  volumes:
  - name: data
    persistentVolumeClaim:
      claimName: pvc-local

