apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: blog
  template:
    metadata:
      labels:
        app: blog
    spec:
      containers:
      - name: blog
        image: skilleat/miniblog:v2-kb5  # ★ 수정
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: blog-config
        env:
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: blog-secret
              key: DB_USER
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: blog-secret
              key: DB_PASS
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 2
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: blog-service
spec:
  type: NodePort
  selector:
    app: blog
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080

