apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog-deploy
spec:
  replicas: 1 
  selector:
    matchLabels: { app: blog }
  template:
    metadata:
      labels: { app: blog }
    spec:
      containers:
      - name: blog
        image: skilleat/miniblog:v2-kb5
        ports: [{ containerPort: 8080 }]
        envFrom:
        - configMapRef:
            name: blog-config
        volumeMounts:
        - name: secret-vol
          mountPath: /etc/secrets
          readOnly: true
      volumes:
      - name: secret-vol
        secret:
          secretName: blog-secret
---
apiVersion: v1
kind: Service
metadata:
  name: blog-service
spec:
  type: NodePort
  selector:
    app: blog
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080

