apiVersion: apps/v1
kind: Deployment
metadata: { name: backend-deploy, namespace: webapp }
spec:
  replicas: 2
  selector: { matchLabels: { app: backend } }
  template:
    metadata: { labels: { app: backend } }
    spec:
      containers:
      - name: backend
        image: skilleat/backend:v3-kb5
        ports: [{ containerPort: 5000 }]
---
apiVersion: v1
kind: Service
metadata: { name: backend-service, namespace: webapp }
spec:
  selector: { app: backend }
  ports:
  - port: 5000
    targetPort: 5000

