apiVersion: v1
kind: Pod
metadata:
  name: test
  labels:
    role: test
spec:
  containers:
    - name: test
      image: busybox
      imagePullPolicy: IfNotPresent
      ports:
        - name: test
          containerPort: 80
          protocol: TCP
      command: ["sh", "-c", "tail -f /dev/null"]
  restartPolicy: Never
  