apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-dp
  labels:
    app: backend-dp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      name: backend
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: skilleat/backend:v1-kb5
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
              protocol: TCP
      restartPolicy: Always